#include "capcom/yaml/yaml_store.hpp"
#include <algorithm>
#include <cctype>
#include <fstream>
#include <set>
#include <sstream>
#include <stdexcept>
namespace capcom::yaml { namespace {
std::string trim(std::string s){auto a=s.find_first_not_of(" \t\r\n");if(a==std::string::npos)return{};auto b=s.find_last_not_of(" \t\r\n");return s.substr(a,b-a+1);}
std::string unquote(std::string s){s=trim(s);if(s.size()>1&&s.front()=='"'&&s.back()=='"')s=s.substr(1,s.size()-2);return s;}
std::vector<std::string> lines(const std::filesystem::path&p){std::ifstream in(p);if(!in)throw std::runtime_error("Cannot read "+p.string());std::vector<std::string>v;std::string s;while(std::getline(in,s)){if(!s.empty()&&s.back()=='\r')s.pop_back();v.push_back(s);}return v;}
void save(const std::filesystem::path&p,const std::vector<std::string>&v){auto t=p;t+=".tmp";{std::ofstream o(t,std::ios::trunc);if(!o)throw std::runtime_error("Cannot write "+t.string());for(auto&s:v)o<<s<<'\n';}std::error_code e;std::filesystem::remove(p,e);e.clear();std::filesystem::rename(t,p,e);if(e)throw std::runtime_error("Cannot replace "+p.string()+": "+e.message());}
std::vector<std::string> inline_list(const std::string&s){auto a=s.find('['),b=s.rfind(']');std::vector<std::string>v;if(a==std::string::npos||b<=a)return v;std::stringstream in{s.substr(a+1,b-a-1)};std::string x;while(std::getline(in,x,',')){x=normalize_uid(unquote(x));if(!x.empty())v.push_back(x);}return v;}
size_t section_end(const std::vector<std::string>&v,size_t start){size_t i=start+1;while(i<v.size()&&(v[i].empty()||v[i][0]==' '||v[i][0]=='\t'))++i;return i;}
void replace_section(const std::filesystem::path&p,const std::string&name,const std::vector<std::string>&block){auto v=lines(p);auto it=std::find_if(v.begin(),v.end(),[&](auto&s){return s.rfind(name+":",0)==0;});if(it!=v.end()){auto pos=static_cast<size_t>(it-v.begin());v.erase(v.begin()+static_cast<long long>(pos),v.begin()+static_cast<long long>(section_end(v,pos)));v.insert(v.begin()+static_cast<long long>(pos),block.begin(),block.end());}else{auto pos=std::find_if(v.begin(),v.end(),[](auto&s){return s.rfind("integration_template:",0)==0;});v.insert(pos,block.begin(),block.end());}save(p,v);}
std::string esc(std::string s){std::string o;for(char c:s){if(c=='"'||c=='\\')o+='\\';if(c=='\n')o+="\\n";else if(c!='\r')o+=c;}return o;}
Item parse(const std::filesystem::path&p){Item r;r.file=p;auto v=lines(p);for(size_t i=0;i<v.size();++i){auto raw=v[i];auto x=raw.find(':');if(x==std::string::npos)continue;auto k=trim(raw.substr(0,x)),val=unquote(raw.substr(x+1));if(k=="uid")r.uid=normalize_uid(val);else if(k=="type")r.type=val;else if(k=="status")r.status=val;else if(k=="title")r.title=val;else if(k=="text")r.text=val;else if(k=="rationale")r.rationale=val;else if(k=="version")r.version=val;else if(k=="git_hash")r.git_hash=val;else if(k=="parents")r.parents=inline_list(raw);else if(k=="children")r.children=inline_list(raw);else if(k=="attributes"){for(size_t j=i+1;j<v.size()&&v[j].rfind("  ",0)==0;++j){auto q=v[j].find(':');if(q!=std::string::npos)r.attributes[trim(v[j].substr(0,q))]=unquote(v[j].substr(q+1));}}else if(k=="implementation"){Implementation z;for(size_t j=i+1;j<v.size()&&v[j].rfind("  ",0)==0;++j){auto q=v[j].find(':');if(q==std::string::npos)continue;auto sk=trim(v[j].substr(0,q));if(sk.rfind("- ",0)==0)sk=trim(sk.substr(2));auto sv=unquote(v[j].substr(q+1));if(sk=="file"){if(!z.file.empty())r.implementations.push_back(z),z={};z.file=sv;}else if(sk=="start_line")z.start_line=std::stoi(sv);else if(sk=="end_line")z.end_line=std::stoi(sv);else if(sk=="git_hash")z.git_hash=sv;}if(!z.file.empty())r.implementations.push_back(z);}else if(k=="test_result"){for(size_t j=i+1;j<v.size()&&v[j].rfind("  ",0)==0;++j){auto q=v[j].find(':');if(q==std::string::npos)continue;auto sk=trim(v[j].substr(0,q)),sv=unquote(v[j].substr(q+1));if(sk=="status")r.test.status=sv;else if(sk=="source")r.test.source=sv;else if(sk=="timestamp")r.test.timestamp=sv;else if(sk=="message")r.test.message=sv;}}}return r;}
}
std::string normalize_uid(std::string s){s=trim(s);std::transform(s.begin(),s.end(),s.begin(),[](unsigned char c){return static_cast<char>(std::toupper(c));});std::replace(s.begin(),s.end(),'_','-');if(s.find('-')==std::string::npos){auto p=std::find_if(s.begin(),s.end(),[](unsigned char c){return std::isdigit(c);});if(p!=s.end())s.insert(p,'-');}return s;}
YamlStore::YamlStore(std::filesystem::path p):project_(std::move(p)){}
std::map<std::string,Item> YamlStore::load_all()const{std::map<std::string,Item>m;auto d=project_/"reqs";if(!std::filesystem::is_directory(d))throw std::runtime_error("reqs directory missing");for(auto&e:std::filesystem::directory_iterator(d)){auto ext=e.path().extension().string();if(e.is_regular_file()&&(ext==".yaml"||ext==".yml")){auto r=parse(e.path());if(r.uid.empty())throw std::runtime_error("Missing uid in "+e.path().string());if(!m.emplace(r.uid,std::move(r)).second)throw std::runtime_error("Duplicate UID: "+r.uid);}}return m;}
void YamlStore::replace_implementations(const std::map<std::string,std::vector<Implementation>>&x)const{auto m=load_all();for(auto&[id,item]:m){std::vector<std::string>b{"implementation:"};auto it=x.find(id);if(it==x.end()||it->second.empty())b={"implementation: []"};else for(auto&z:it->second){b.push_back("  - file: \""+esc(z.file)+"\"");b.push_back("    start_line: "+std::to_string(z.start_line));b.push_back("    end_line: "+std::to_string(z.end_line));b.push_back("    git_hash: \""+esc(z.git_hash)+"\"");}replace_section(item.file,"implementation",b);}}
void YamlStore::update_test(const std::string&id0,const TestResult&r)const{auto m=load_all();const auto id=normalize_uid(id0);auto it=m.find(id);if(it==m.end())throw std::runtime_error("Test UID not found: "+id);replace_section(it->second.file,"test_result",{"test_result:","  status: "+r.status,"  source: \""+esc(r.source)+"\"","  timestamp: \""+esc(r.timestamp)+"\"","  message: \""+esc(r.message)+"\""});}
std::vector<std::string> YamlStore::validate(const std::map<std::string,Item>&m)const{std::vector<std::string>e;for(auto&[id,r]:m){auto need=[&](auto&v,const char*n){if(v.empty())e.push_back(id+": missing "+n);};need(r.uid,"uid");need(r.type,"type");need(r.status,"status");need(r.title,"title");need(r.text,"text");need(r.rationale,"rationale");need(r.version,"version");if((r.type=="SRS"||r.type=="ARCH"||r.type=="LLD")){if(!r.attributes.contains("iec62304_class"))e.push_back(id+": missing attributes.iec62304_class");if(!r.attributes.contains("justification"))e.push_back(id+": missing attributes.justification");}for(auto&p:r.parents){auto it=m.find(p);if(it==m.end())e.push_back(id+": missing parent "+p);else if(std::find(it->second.children.begin(),it->second.children.end(),id)==it->second.children.end())e.push_back(id+": asymmetric parent link "+p);}for(auto&c:r.children){auto it=m.find(c);if(it==m.end())e.push_back(id+": missing child "+c);else if(std::find(it->second.parents.begin(),it->second.parents.end(),id)==it->second.parents.end())e.push_back(id+": asymmetric child link "+c);}}return e;}
}
