#include "capcom/commands/manual_commands.hpp"
#include "capcom/audit/history_service.hpp"
#include "capcom/identity/identity_manager.hpp"
#include "capcom/yaml/yaml_store.hpp"
#include <cstdlib>
#include <iostream>
#include <stdexcept>
namespace capcom::commands { namespace {capcom::yaml::Item find(const std::filesystem::path&p,const std::string&u){auto id=capcom::yaml::normalize_uid(u);auto m=capcom::yaml::YamlStore{p}.load_all();auto i=m.find(id);if(i==m.end())throw std::runtime_error("Item not found: "+id);return i->second;}}
int SignCommand::execute(const std::filesystem::path&p,const std::string&u,const std::string&r)const{if(r.empty())throw std::runtime_error("A change reason is required.");auto item=find(p,u);auto id=capcom::identity::IdentityManager{}.load_or_create();capcom::audit::HistoryService h{id};auto existing=h.entries(item.file,item.uid);if(existing.empty()){h.append(item.file,item.uid,"ITEM_CREATED",r);h.verify_file(item.file,item.uid);std::cout<<"Initialized signed history for "<<item.uid<<".\\n";return 0;}h.verify_history_chain(item.file,item.uid);if(!h.has_unsigned_content_changes(item.file,item.uid)){std::cout<<item.uid<<" has no unsigned content changes.\n";return 0;}h.append(item.file,item.uid,"CONTENT_UPDATED",r);h.verify_file(item.file,item.uid);std::cout<<"Signed manual YAML changes for "<<item.uid<<".\n";return 0;}
int DiffCommand::execute(const std::filesystem::path&p,const std::optional<std::string>&u)const{auto items=capcom::yaml::YamlStore{p}.load_all();auto id=capcom::identity::IdentityManager{}.load_or_create();capcom::audit::HistoryService h{id};int changed=0;for(auto&[uid,item]:items){if(u&&capcom::yaml::normalize_uid(*u)!=uid)continue;h.verify_history_chain(item.file,uid);if(!h.has_unsigned_content_changes(item.file,uid)){if(u)std::cout<<uid<<" has no unsigned content changes.\n";continue;}++changed;std::cout<<uid<<"  "<<item.title<<"\n";if(u){std::cout<<"  Last signed: "<<h.latest_signed_content_hash(item.file)<<"\n  Current:     "<<h.current_content_hash(item.file)<<"\n";auto c="git --no-pager diff -- \""+item.file.string()+"\"";std::system(c.c_str());}}if(!u)std::cout<<changed<<" item(s) require signing.\n";return changed?1:0;}
}
