#include "captain/storage/local_yaml_storage.hpp"
#include <algorithm>
#include <cctype>
#include <fstream>
#include <iomanip>
#include <regex>
#include <sstream>
#include <stdexcept>
namespace captain::storage {namespace {
std::string upper(std::string s){std::transform(s.begin(),s.end(),s.begin(),[](unsigned char c){return static_cast<char>(std::toupper(c));});return s;}
std::string lower(std::string s){std::transform(s.begin(),s.end(),s.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));});return s;}
std::string trim(std::string s){const auto a=s.find_first_not_of(" \t\r\n");if(a==std::string::npos)return{};const auto b=s.find_last_not_of(" \t\r\n");return s.substr(a,b-a+1);}
std::string unquote(std::string s){s=trim(s);if(s.size()>1&&s.front()=='"'&&s.back()=='"')s=s.substr(1,s.size()-2);return s;}
std::string quote(const std::string&s){std::string o="\"";for(char c:s){if(c=='\\'||c=='"')o+='\\';o+=c;}return o+'"';}
std::vector<std::string> list(const std::string&s){const auto a=s.find('['),b=s.rfind(']');std::vector<std::string>v;if(a==std::string::npos||b<=a)return v;std::stringstream in{s.substr(a+1,b-a-1)};std::string x;while(std::getline(in,x,',')){x=upper(unquote(x));if(!x.empty())v.push_back(x);}return v;}
std::string render_list(const std::vector<std::string>&v){std::ostringstream o;o<<'[';for(std::size_t i=0;i<v.size();++i){if(i)o<<", ";o<<v[i];}o<<']';return o.str();}
void render_attributes(std::ostream&o,const domain::Requirement&r){o<<"attributes:\n";if(r.type=="SRS"||r.type=="SEC")o<<"  classification_ref: \"\"\n  software_item_safety_class: \"\"\n  classification_responsible: \"\"\n  classification_rationale: \"\"\n  risk_references: []\n";else if(r.type=="UT"||r.type=="IT"||r.type=="ST"||r.type=="AT"||r.type=="TEST")o<<"  verifies: []\n  test_method: \"\"\n  expected_result: \"\"\n  test_responsible: \"\"\n";else o<<"  owner: \"\"\n";}
domain::Requirement parse(const std::filesystem::path&p){domain::Requirement r;r.authority=domain::Authority::local;std::ifstream in(p);std::string line;while(std::getline(in,line)){const auto c=line.find(':');if(c==std::string::npos)continue;const auto k=trim(line.substr(0,c)),v=unquote(line.substr(c+1));const bool top=!line.empty()&&line.front()!=' '&&line.front()!='\t';if(top&&k=="uid")r.uid=upper(v);else if(top&&k=="type")r.type=upper(v);else if(top&&k=="status")r.status=v;else if(top&&k=="title")r.title=v;else if(top&&k=="text")r.text=v;else if(top&&k=="rationale")r.rationale=v;else if(top&&k=="parents")r.parents=list(line);else if(top&&k=="children")r.children=list(line);else if(top&&k=="authority")r.authority=v=="remote"?domain::Authority::remote:domain::Authority::local;else if(top&&k=="read_only")r.read_only=v=="true";}return r;}
void write(const std::filesystem::path&p,const domain::Requirement&r){std::filesystem::create_directories(p.parent_path());auto t=p;t+=".tmp";std::ofstream o(t,std::ios::binary|std::ios::trunc);if(!o)throw std::runtime_error("Cannot write "+t.string());o<<"uid: "<<r.uid<<"\ntype: "<<r.type<<"\nstatus: "<<r.status<<"\ntitle: "<<quote(r.title)<<"\ntext: "<<quote(r.text)<<"\nrationale: "<<quote(r.rationale)<<"\nversion: \"0.1.0\"\ngit_hash: null\nauthority: "<<domain::authority_name(r.authority)<<"\nread_only: "<<(r.read_only?"true":"false")<<"\n";render_attributes(o,r);o<<"parents: "<<render_list(r.parents)<<"\nchildren: "<<render_list(r.children)<<"\nimplementation: []\nintegration_template: |\n  /* @cap-start: "<<r.uid<<"\n   * @cap-desc: "<<r.title<<"\n   */\n  /* @cap-end: "<<r.uid<<" */\n";o.close();std::error_code ec;std::filesystem::remove(p,ec);ec.clear();std::filesystem::rename(t,p,ec);if(ec)throw std::runtime_error("Cannot replace "+p.string());}
std::filesystem::path path_for(const std::filesystem::path&project,const domain::Requirement&r){const auto dir=project/"reqs"/lower(r.type);const auto yaml=dir/(r.uid+".yaml");if(std::filesystem::exists(yaml))return yaml;const auto yml=dir/(r.uid+".yml");return std::filesystem::exists(yml)?yml:yaml;}
}
LocalYamlStorage::LocalYamlStorage(std::filesystem::path p):project_(std::move(p)){}
bool LocalYamlStorage::writable(const std::string&t)const noexcept{const auto u=upper(t);return u=="USR"||u=="SYS"||u=="SRS"||u=="SEC"||u=="ARCH"||u=="LLD"||u=="TEST"||u=="UT"||u=="IT"||u=="ST"||u=="AT"||u=="BUG";}
std::vector<domain::Requirement> LocalYamlStorage::all()const{std::vector<domain::Requirement>v;const auto root=project_/"reqs";if(!std::filesystem::exists(root))return v;for(const auto&e:std::filesystem::recursive_directory_iterator(root)){const auto x=e.path().extension().string();if(e.is_regular_file()&&(x==".yml"||x==".yaml")&&e.path().filename()!="captainslog.yml"){auto r=parse(e.path());if(r.authority!=domain::Authority::remote)v.push_back(std::move(r));}}return v;}
std::optional<domain::Requirement> LocalYamlStorage::find(const std::string&uid)const{for(auto&r:all())if(r.uid==upper(uid))return r;return std::nullopt;}
domain::Requirement LocalYamlStorage::create(const domain::CreateRequirement&q){const auto type=upper(q.type);if(!writable(type))throw std::runtime_error("Type is not local: "+type);const auto dir=project_/"reqs"/lower(type);std::filesystem::create_directories(dir);int n=0;const std::regex re{"^"+type+R"(-(\d+)\.(yaml|yml)$)"};for(const auto&e:std::filesystem::directory_iterator(dir)){std::smatch m;const auto f=e.path().filename().string();if(std::regex_match(f,m,re))n=std::max(n,std::stoi(m[1].str()));}std::ostringstream id;id<<type<<'-'<<std::setw(3)<<std::setfill('0')<<n+1;domain::Requirement r;r.uid=id.str();r.type=type;r.status="Draft";r.title=q.title;r.text=q.text;r.rationale=q.rationale;r.authority=domain::Authority::local;r.parents=q.parents;r.children=q.children;r.revision="1";r.updated_by="web-user";write(dir/(r.uid+".yaml"),r);return r;}
void LocalYamlStorage::update(const domain::Requirement&r){if(r.read_only)throw std::runtime_error("Remote mirror is read-only: "+r.uid);write(path_for(project_,r),r);}
void LocalYamlStorage::write_mirror(const domain::Requirement&r){auto m=r;m.authority=domain::Authority::remote;m.read_only=true;write(project_/"reqs"/"remote"/lower(r.type)/(r.uid+".yaml"),m);}
}
