#include "captain/storage/sqlite_management_storage.hpp"
#include <sqlite3.h>
#include <chrono>
#include <iomanip>
#include <sstream>
#include <stdexcept>
namespace captain::storage {namespace {
void check(int rc,sqlite3*db){if(rc!=SQLITE_OK&&rc!=SQLITE_DONE&&rc!=SQLITE_ROW)throw std::runtime_error(sqlite3_errmsg(db));}
std::string now(){auto t=std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());std::tm x{};
#ifdef _WIN32
 gmtime_s(&x,&t);
#else
 gmtime_r(&t,&x);
#endif
 std::ostringstream o;o<<std::put_time(&x,"%Y-%m-%dT%H:%M:%SZ");return o.str();}
std::string id(const char*p){return std::string{p}+std::to_string(std::chrono::high_resolution_clock::now().time_since_epoch().count());}
void exec(sqlite3*d,const char*s){char*e=nullptr;int rc=sqlite3_exec(d,s,nullptr,nullptr,&e);if(rc!=SQLITE_OK){std::string m=e?e:"sqlite error";sqlite3_free(e);throw std::runtime_error(m);}}
}
SqliteManagementStorage::SqliteManagementStorage(const std::filesystem::path&p){if(sqlite3_open(p.string().c_str(),&db_)!=SQLITE_OK)throw std::runtime_error("Cannot open management database");schema();}
SqliteManagementStorage::~SqliteManagementStorage(){if(db_)sqlite3_close(db_);}
void SqliteManagementStorage::schema(){exec(db_,"CREATE TABLE IF NOT EXISTS requirements(uid TEXT PRIMARY KEY,type TEXT,status TEXT,title TEXT,text TEXT,rationale TEXT,revision INTEGER DEFAULT 1,updated_at TEXT,updated_by TEXT);CREATE TABLE IF NOT EXISTS comments(id TEXT PRIMARY KEY,requirement_uid TEXT,author TEXT,created_at TEXT,text TEXT);CREATE TABLE IF NOT EXISTS file_links(id TEXT PRIMARY KEY,requirement_uid TEXT,kind TEXT,label TEXT,location TEXT,version TEXT,hash TEXT,created_at TEXT,created_by TEXT);");}
bool SqliteManagementStorage::writable(const std::string&t)const noexcept{return t=="RISK"||t=="CLASS"||t=="CR"||t=="SOUP";}
std::vector<domain::Requirement> SqliteManagementStorage::all()const{std::vector<domain::Requirement>v;sqlite3_stmt*s{};check(sqlite3_prepare_v2(db_,"SELECT uid,type,status,title,text,rationale,revision,updated_at,updated_by FROM requirements ORDER BY uid",-1,&s,nullptr),db_);while(sqlite3_step(s)==SQLITE_ROW){domain::Requirement r;r.uid=reinterpret_cast<const char*>(sqlite3_column_text(s,0));r.type=reinterpret_cast<const char*>(sqlite3_column_text(s,1));r.status=reinterpret_cast<const char*>(sqlite3_column_text(s,2));r.title=reinterpret_cast<const char*>(sqlite3_column_text(s,3));r.text=reinterpret_cast<const char*>(sqlite3_column_text(s,4));r.rationale=reinterpret_cast<const char*>(sqlite3_column_text(s,5));r.authority=domain::Authority::remote;r.read_only=true;r.revision=std::to_string(sqlite3_column_int(s,6));r.updated_at=reinterpret_cast<const char*>(sqlite3_column_text(s,7));r.updated_by=reinterpret_cast<const char*>(sqlite3_column_text(s,8));v.push_back(r);}sqlite3_finalize(s);return v;}
std::optional<domain::Requirement> SqliteManagementStorage::find(const std::string&u)const{for(auto&r:all())if(r.uid==u)return r;return std::nullopt;}
domain::Requirement SqliteManagementStorage::create(const domain::CreateRequirement&q){if(!writable(q.type))throw std::runtime_error("Type is not remote: "+q.type);int n=1;for(auto&r:all())if(r.type==q.type)++n;std::ostringstream uid;uid<<q.type<<'-'<<std::setw(3)<<std::setfill('0')<<n;auto time=now();sqlite3_stmt*s{};check(sqlite3_prepare_v2(db_,"INSERT INTO requirements(uid,type,status,title,text,rationale,updated_at,updated_by) VALUES(?,?,?,?,?,?,?,?)",-1,&s,nullptr),db_);sqlite3_bind_text(s,1,uid.str().c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,q.type.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,"Draft",-1,SQLITE_STATIC);sqlite3_bind_text(s,4,q.title.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,5,q.text.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,6,q.rationale.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,7,time.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,8,"web-user",-1,SQLITE_STATIC);check(sqlite3_step(s),db_);sqlite3_finalize(s);return *find(uid.str());}
void SqliteManagementStorage::update(const domain::Requirement&){throw std::runtime_error("Update endpoint not implemented in MVP");}
std::vector<domain::Comment> SqliteManagementStorage::comments(const std::string&u)const{std::vector<domain::Comment>v;sqlite3_stmt*s{};check(sqlite3_prepare_v2(db_,"SELECT id,requirement_uid,author,created_at,text FROM comments WHERE requirement_uid=? ORDER BY created_at",-1,&s,nullptr),db_);sqlite3_bind_text(s,1,u.c_str(),-1,SQLITE_TRANSIENT);while(sqlite3_step(s)==SQLITE_ROW)v.push_back({reinterpret_cast<const char*>(sqlite3_column_text(s,0)),reinterpret_cast<const char*>(sqlite3_column_text(s,1)),reinterpret_cast<const char*>(sqlite3_column_text(s,2)),reinterpret_cast<const char*>(sqlite3_column_text(s,3)),reinterpret_cast<const char*>(sqlite3_column_text(s,4))});sqlite3_finalize(s);return v;}
domain::Comment SqliteManagementStorage::add_comment(const std::string&u,const std::string&a,const std::string&t){domain::Comment c{id("C-"),u,a,now(),t};sqlite3_stmt*s{};check(sqlite3_prepare_v2(db_,"INSERT INTO comments VALUES(?,?,?,?,?)",-1,&s,nullptr),db_);sqlite3_bind_text(s,1,c.id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,u.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,a.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,4,c.created_at.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,5,t.c_str(),-1,SQLITE_TRANSIENT);check(sqlite3_step(s),db_);sqlite3_finalize(s);return c;}
std::vector<domain::FileLink> SqliteManagementStorage::files(const std::string&u)const{std::vector<domain::FileLink>v;sqlite3_stmt*s{};check(sqlite3_prepare_v2(db_,"SELECT id,requirement_uid,kind,label,location,version,hash,created_at,created_by FROM file_links WHERE requirement_uid=?",-1,&s,nullptr),db_);sqlite3_bind_text(s,1,u.c_str(),-1,SQLITE_TRANSIENT);while(sqlite3_step(s)==SQLITE_ROW){domain::FileLink f;auto col=[&](int i){auto x=reinterpret_cast<const char*>(sqlite3_column_text(s,i));return std::string{x?x:""};};f.id=col(0);f.requirement_uid=col(1);f.kind=col(2);f.label=col(3);f.location=col(4);f.version=col(5);f.hash=col(6);f.created_at=col(7);f.created_by=col(8);v.push_back(f);}sqlite3_finalize(s);return v;}
domain::FileLink SqliteManagementStorage::add_file(const domain::FileLink&x){auto f=x;f.id=id("F-");f.created_at=now();if(f.created_by.empty())f.created_by="web-user";sqlite3_stmt*s{};check(sqlite3_prepare_v2(db_,"INSERT INTO file_links VALUES(?,?,?,?,?,?,?,?,?)",-1,&s,nullptr),db_);const std::string* fields[]={&f.id,&f.requirement_uid,&f.kind,&f.label,&f.location,&f.version,&f.hash,&f.created_at,&f.created_by};for(int i=0;i<9;++i)sqlite3_bind_text(s,i+1,fields[i]->c_str(),-1,SQLITE_TRANSIENT);check(sqlite3_step(s),db_);sqlite3_finalize(s);return f;}
}
